version: "3"

services:
  ng_frontend:
    container_name: ng_frontend
    build:
      context: "./NG_Frontend"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "./NG_Frontend:/usr/app"
    
    networks:
      - NG_network
    depends_on:
      - ng_backend
    

  ng_backend:
    env_file:
      - "./NG_Backend/.env"
    container_name: ng_backend
    build:
      context: "./NG_Backend"
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - ng_database

    volumes:
      - "./NG_Backend:/usr/app"
    networks:
      - NG_network
    command:  bash -c "npm run migrate && npm run dev"

  ng_database:
    container_name: ng_database
    image: postgres

    env_file:
      #You must be especify db, user and password for the database
      #in .env file into NG_Backend
      - ./NG_Backend/.env

    ports:
      - 5432:5432
    networks:
      - NG_network

networks:
  NG_network:
    driver: bridge
      
